#!/bin/bash

select filename in `ls *.startmux`
do
    echo $filename
    if [ -f "$filename" ]; then
        echo ""
        echo "Loading $filename file"
        . $filename
        break
    else
        echo ""
        echo "Invalid selection"
    fi
done

tmux start-server
windownumber=0
for window in ${!combo[@]}; do
    name=${window}
    command=${combo[$window]}
    if [ $((windownumber%2)) == 0 ]; then
        tmux new-session -d -s startmux -n "${name}"
    else
        tmux new-window -tstartmux:$windownumber -n "${name}"
    fi
    tmux send-keys -tstartmux:$windownumber "${command}" C-m
    ((windownumber++))
done
tmux select-window -tstartmux:0
tmux attach-session -d -tstartmux
