#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    TARGET="$(readlink "$SOURCE")"
    if [[ $SOURCE == /* ]]; then
        SOURCE="$TARGET"
    else
        ttmux="$( dirname "$SOURCE" )"
        SOURCE="$ttmux/$TARGET"
    fi
done
RDIR="$( dirname "$SOURCE" )"
ttmux="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. $ttmux/"lib/colors"
. $ttmux/"lib/utils"

ensure_tmux_is_installed
ttmux_header

argument=$1
if [ $1 == '-l' ]; then
    show_ttmux_files
    exit
fi

if [ -f "$1" ]; then
    echo "${information}Configuration sent via parameters${reset}"
    . "$1"
else
    echo "${information}Retrieving local information ...${reset}"
    if [[ -n $(ls *.ttmux) ]]; then
        echo "${information}Configuration files found${reset}"
        found=$(ls -l *.ttmux|wc -l)
    else
        echo "${alert}No configuration available in folder $PWD${reset}"
        exit
    fi

    configurationLoaded=0
    if [ $found == 1 ]; then
        filename=$(ls *.ttmux)
        if [ -f "$filename" ]; then
            . $filename
            configurationLoaded=1
        fi
    fi

    if [ $configurationLoaded == 0 ]; then
        echo "${information}Select your configuration file here${reset}"
        select filename in `ls *.ttmux`
        do
            echo $filename
            if [ -f "$filename" ]; then
                echo ""
                echo "Loading $filename file"
                . $filename
                break
            else
                echo ""
                echo "Invalid selection"
            fi
        done
    fi
fi


tmux start-server
start=1
windownumber=$start
if [ -z "$order" ]; then windows=${!combo[@]}; else windows=${order[@]}; fi
for window in $windows; do
    name=${window}
    command=${combo[$window]}
    if [ $((windownumber)) == $start ]; then
        tmux new-session -d -s startmux -n "${name}"
    else
        tmux new-window -tstartmux:$windownumber -n "${name}"
    fi
    tmux send-keys -tstartmux:$windownumber "${command}" C-m
    ((windownumber++))
done
tmux select-window -tstartmux:$start
tmux attach-session -d -tstartmux
