#!/bin/bash

function ensure_tmux_is_installed {
    echo "${information}Retrieving local information ...${reset}"
    if [[ -n $(which tmux) ]]; then
        echo "${information}Tmux is installed in your system${reset}"
    else
        echo "${alert}Tmux is not installed${reset}"
        echo "${information}run apt-get install tmux${reset}"
        exit
    fi
}

function ensure_configuration_file_is_ok {
    if [[ -z ${#horizontal_panes[@]+x} ]]; then
        echo ""
        echo "    ${alert}horizontal_panes is not defined inside configuration file${reset}"
        echo "    ${information}declare -A horizontal_panes=()${reset}"
        echo ""
        exit
    fi
    if [[ -z ${session_name+x} ]]; then
        echo ""
        echo "    ${alert}session_name is not defined inside configuration file${reset}"
        echo ""
        exit
    fi
    if [[ 0 = ${#window_list[@]} ]]; then
        echo ""
        echo "    ${alert}window_list is not defined inside configuration file${reset}"
        echo ""
        exit
    fi
    if [[ 0 = ${#ordered_windows[@]} ]]; then
        echo ""
        echo "    ${alert}ordered_windows is not defined inside configuration file${reset}"
        echo ""
        exit
    fi
}

function show_ttmux_files {
    ls -l *.ttmux
    echo ""
}

function ttmux_header {

    clear

    echo ""

    if [[ -n $(which figlet) ]]; then
        figlet ttmux-alfa
    else
        echo "You are loading default configuration"
        echo "                                     "
        echo "    __    __                         "
        echo "  _/  |__/  |_  _____  __ _____  ___ "
        echo "  \   __\   __\/     \|  |  \  \/  / "
        echo "   |  |  |  | |  Y Y  \  |  />    <  "
        echo "   |__|  |__| |__|_|  /____//__/\_ \ "
        echo "                    \/            \/ "
        echo ""
        echo "http://www.network-science.de/ascii/ "
        echo ""
    fi

    echo ""

}

function show_ttmux_help {
    ttmux_header
    echo ""
    echo ""
    echo "$ ttmux"
    echo "${information}"
    echo "    ttmux default behavior, look for all .ttmux files and when only one is preset is opened."
    echo "    if zero ttmux file are present, a message will be displayed"
    echo "    if more ttmux files are found, a menu will help developer to choose one of them"
    echo "${reset}"
    echo ""
    echo ""
    echo "$ ttmux -l"
    echo "${information}"
    echo "    this command will display all ttmux files present in current folder"
    echo "${reset}"
    echo ""
    echo ""
    echo "$ ttmux -h"
    echo "${information}"
    echo "    this command show this help"
    echo "${reset}"
    echo ""
    echo ""
    echo "$ ttmux config.ttmux"
    echo "${information}"
    echo "    if a developer know the name of configuration file, can open it directly"
    echo "${reset}"
    echo ""
    echo ""
}
